# Jekyll 설정
title: Learn CS
description: Computer Science learning materials
url: "https://lledellebell.github.io"
baseurl: "/learn-cs"
repository: lledellebell/learn-cs
author: Learn CS

# SEO 설정
lang: ko_KR
timezone: Asia/Seoul

# Social Links (선택사항 - 필요시 추가)
# twitter:
#   username: your_username
# social:
#   name: Learn CS
#   links:
#     - https://github.com/lledellebell/learn-cs

# Default image for social sharing (선택사항 - 이미지 추가 시 주석 해제)
# logo: /assets/images/logo.png

# 빌드 설정
markdown: kramdown
highlighter: rouge

# GitHub Pages 기본 테마
theme: jekyll-theme-primer

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-last-modified-at

# 제외할 파일/폴더
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
  - package.json
  - package-lock.json
  - .gitignore
  - .gitmodules
  - LICENSE
  - private
  - private_backup_*
  - mcp-servers
  - "*.log"
  - .vscode
  - .idea
  - .DS_Store

# Sitemap 설정
sitemap:
  priority: 0.7
  changefreq: weekly

# 포함할 파일 패턴
include:
  - .htaccess
  - _pages
  - .learning-history.json

# 빈 파일 처리 (엄격하지 않게)
strict_front_matter: false

# 마크다운 설정
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# 제목 자동 생성
titles_from_headings:
  enabled: true
  strip_title: false
  collections: false

# 상대 링크 처리
relative_links:
  enabled: true
  collections: false

# Liquid 템플릿 비활성화 (코드 예제의 {{ }} 구문 보호)
# 기술 문서 디렉토리만 선택적으로 적용
defaults:
  # All pages default layout
  - scope:
      path: ""
    values:
      layout: "page"
  # Home page
  - scope:
      path: "index.md"
    values:
      layout: "home"
  # Disable Liquid for code examples
  - scope:
      path: "web-development"
    values:
      render_with_liquid: false
      layout: "page"
  - scope:
      path: "languages"
    values:
      render_with_liquid: false
      layout: "page"
  - scope:
      path: "databases"
    values:
      render_with_liquid: false
      layout: "page"
  - scope:
      path: "algorithms"
    values:
      render_with_liquid: false
      layout: "page"
  - scope:
      path: "networking"
    values:
      render_with_liquid: false
      layout: "page"
  - scope:
      path: "news"
    values:
      render_with_liquid: false
      layout: "page"
